name: fortress_of_the_muslim
description: Fortress of the Muslim

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0-beta.2
  html: 0.15.4
  step_progress_indicator: ^1.0.2
  flutter_material_color_picker: ^1.2.0
  responsive_builder: ^0.7.1

  # Databases
  sqflite: ^2.4.1
  hive_flutter: ^1.1.0

  # System
  wakelock_plus: ^1.2.8
  vibration: ^2.0.1

  # Path
  path: ^1.9.0

  # Copy/Share
  clipboard: ^0.1.3
  share_plus: ^10.1.2

  # Notifications
  flutter_local_notifications: ^18.0.1

  # State management
  provider: ^6.1.2

  # Times
  intl: ^0.19.0
  timezone: ^0.10.0

  # Audio
  just_audio: ^0.9.42

  # Url
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audios/
    - assets/databases/
    - assets/fonts/
    - assets/icons/
    - assets/pictures/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
    - family: SF Pro
      fonts:
        - asset: assets/fonts/sf_pro_regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf
    - family: Noto Naskh
      fonts:
        - asset: assets/fonts/noto_naskh_regular.ttf
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf