name: fortress_of_the_muslim
description: Fortress of the Muslim

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  path_provider: ^2.0.15
  flutter_html: ^3.0.0-beta.2
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  step_progress_indicator: ^1.0.2
  share_plus: ^7.0.2
  clipboard: ^0.1.3
  vibration: ^1.8.1
  url_launcher: ^6.1.12
  flu_wake_lock: ^0.0.2
  just_audio: ^0.9.34
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  intl: ^0.18.1
  flutter_material_color_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pictures/
    - assets/databases/
    - assets/audios/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
        - asset: assets/fonts/gilroy_light.ttf
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa_reqular.ttf
    - family: Verdana
      fonts:
        - asset: assets/fonts/verdana.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/quran_font.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri_reqular.ttf
