name: fortress_of_the_muslim
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  flutter_html: ^2.2.1
  provider: ^6.0.3
  url_launcher: ^6.1.2
  wakelock: ^0.6.1+2
  shared_preferences: ^2.0.15
  share_plus: ^4.0.7
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
     - assets/audios/
     - assets/databases/
     - assets/fonts/
     - assets/icons/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf