name: fortress_of_the_muslim
description: Fortress of the muslim
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  flutter_html: ^2.2.1
  provider: ^6.0.3
  url_launcher: ^6.1.5
  wakelock: ^0.6.2
  share_plus: ^4.0.10
  clipboard: ^0.1.3
  just_audio: ^0.9.28
  o_color_picker: ^1.0.2
  draggable_fab: ^0.1.4
  percent_indicator: ^4.2.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
     - assets/audios/
     - assets/databases/
     - assets/fonts/
     - assets/icons/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_light.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri_reqular.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/quran_font.ttf
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri_reqular.ttf
    - family: Times
      fonts:
        - asset: assets/fonts/times_new_roman.ttf