name: fortress_of_the_muslim
description: Fortress of the Muslim

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.6
  step_progress_indicator: ^1.0.2
  flutter_material_color_picker: ^1.2.0
  responsive_builder: ^0.7.1

  # Databases
  sqflite: ^2.4.2
  hive_flutter: ^1.1.0

  # System
  wakelock_plus: ^1.3.2
  vibration: ^3.1.3

  # Path
  path: ^1.9.1
  path_provider: ^2.1.5

  # Copy/Share
  clipboard: ^0.1.3
  share_plus: ^11.0.0

  # Notifications
  flutter_local_notifications: ^19.3.0

  # State management
  provider: ^6.1.5

  # Times
  intl: ^0.20.2
  timezone: ^0.10.1

  # Audio
  just_audio: ^0.10.4

  # Url
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_gen:
  output: lib/gen/
  synthetic_package: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audios/
    - assets/databases/
    - assets/fonts/
    - assets/icons/
    - assets/pictures/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
    - family: SF Pro
      fonts:
        - asset: assets/fonts/sf_pro_regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf
    - family: Noto Naskh
      fonts:
        - asset: assets/fonts/noto_naskh_regular.ttf
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf