name: fortress_of_the_muslim
description: Fortress Of The Muslim

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flip_box_bar_plus: ^0.9.3+2
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3
  flutter_html: ^1.3.0
  audioplayers: ^0.18.3
  share: ^2.0.1
  clipboard: ^0.1.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  vibration: ^1.7.3
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/audios/
    - assets/databases/
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf