name: fortress_of_the_muslim
description: Fortress of the Muslim

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0-beta.2
  step_progress_indicator: ^1.0.2
  flutter_material_color_picker: ^1.2.0

  # Databases
  sqflite: ^2.4.0
  hive_flutter: ^1.1.0

  # System
  wakelock_plus: ^1.2.8
  vibration: ^2.0.0

  # Path
  path: ^1.9.0
  path_provider: ^2.1.4

  # Copy/Share
  clipboard: ^0.1.3
  share_plus: ^10.0.3

  # Notifications
  flutter_local_notifications: ^17.2.3

  # State management
  provider: ^6.1.2

  # Times
  intl: ^0.19.0
  timezone: ^0.9.4

  # Audio
  just_audio: ^0.9.41

  # Url
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pictures/
    - assets/databases/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_light.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/hafs.ttf